version: "3"
services:
    app:        
        build: 
            context: .
            dockerfile: Dockerfile
        #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
        command: tail -f /dev/null
        volumes:
            - .:/home/node/app
        ports:
            - "127.0.0.1:3000:3000" # main app
            - "3035:3035" # webpack-dev-server
            - "35729:35729" # livereload
        container_name: billboard